### PR TITLE
Upgrade to Dart 2

### PR DESCRIPTION
**Pull request by chalin**
cc @kwalrath @kevmoo

### CODE REVIEW

**Comment by filiph** [comment]
Thank you!

The Travis built failed because Dart 2 is not installed (or even installable?) via Travis. Looks like a larger issue.

**Comment by chalin** [comment]
> The Travis built failed ...

Oops, my bad. I've fixed the script (and added a run of the analyzer and dartfmt), and Travis is green now.

Shall I label this 2.0.0 (or do you still prefer that it be 2.0.0-dev.1)?

**Comment by filiph** [comment]
I'm fine with 2.0 if you are.

**Comment by chalin** [comment]
2.0.0 works for me. I'll make that change now. Will you be in a position to merge this after that?

**Comment by chalin** [comment]
(Or if you grant me the permissions to merge and publish, I can do it. I also don't mind awaiting your return.)

**Comment by filiph** [comment]
Sorry for the delay. I've merged. I'll also give you write access to this repo.

**Comment by chalin** [comment]
> Sorry for the delay. I've merged. I'll also give you write access to this repo.

Np. Thanks! (Can you publish as well? I don't think permission on the repo applies to pub permissions?)

**Comment by chalin** [comment]
I just tried to publish, and can confirm that I don't have the authorization to do so.

**Comment by filiph** [comment]
You are now also uploader of `linkcheck`. I'll leave the publishing to you this time. I'm on a train and about to disappear into vacationland soon.

**Comment by chalin** [comment]
🎉 🚋🚋🚋🚋... 🏖 🌞

**Pull request merged**
