### PR TITLE
Fix invalid syntax of github action file

### PR DESCRIPTION
**Pull request by errnesto**
Okay I'm very sorry for my messy contributions :-( The github action is still broken.
I'm trying to clean it up here.

The last time. I tested the action locally with https://github.com/nektos/act where it worked fine, but the syntax for the action was still invalid.

By now I don't know if there is a good way to do this with only an action file.
So I created a entrypoint.sh file and another Dockerfile.
There it is easier to access the input variables from github.

And I added a "test" here:
https://github.com/wunderundfitzig/linkcheck-action/runs/4301401999?check_suite_focus=true

### CODE REVIEW

**Comment by andrenarchy** [comment]
It would be great to see this merged and in a new release as soon as possible because the action is not usable for us currently.

**Comment by errnesto** [comment]
@filiph ping :-)
I’m also happy to apply some changes to this. e.g. if you would prefer to use just one Dockerfile. Then the entrypoint.sh would just go unused in the normal case.

**Comment by filiph** [comment]
Thanks for the ping! To be honest, I don't know enough about Docker to review this. I hoped I'd have time by now to learn more, but I don't. I'll just merge it. Please let me know if there's anything else I need to do.

**Comment by tooomm** [comment]
@filiph Since your published action is sadly still not working in the GitHub Marketplace... do you mind trying to publish a new release?
All changes in recent month (like this one) that are targeting at fixing the action are not yet in a published release.

I've to admit that I'm not sure if that solves the issue and I never created an Action myself... but it sounds not too far fetched and is definitely worth trying.

**Pull request merged**
